# Form implementation generated from reading ui file 'untitled2.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt
# from PySide6.QtWidgets import QTableView, QApplication, QMessageBox
# from PySide6.QtCore import QAbstractTableModel, Qt, QModelIndex
import pandasway_w_class as pd_obj
import csv
import pandas as pd

studentsFile = 'students.csv'
courseFile = 'course.csv'
tableStyleSheet = """
            QTableView {
                background-color: rgb(39, 41, 50);
                color: white;
                border: 2px solid rgb(130, 132, 137);
            }
            QHeaderView::section {
                background-color: rgb(39, 41, 50);
                color: white;
            }
            QTableCornerButton::section {
                background-color: rgb(39, 41, 50);
                color: white;
            }
            QHeaderView::section:hover {
                background-color: rgb(241, 234, 208);
                color: rgb(39, 41, 50);
            }
            QTableView::item:hover {
                background-color: rgb(241, 234, 208);
                color: rgb(39, 41, 50);
            }
            QTableView::item:selected {
                background-color: rgb(245, 241, 224);
                color: rgb(39, 41, 50);
            }
        """


class CoursePopUp(QtWidgets.QDialog):
    def __init__(self, parent, courseList, combo_string):
        super().__init__(parent)
        self.setWindowTitle("Choose new Course")
        self.setFixedWidth(200)
        self.setFixedHeight(100)

        layout = QtWidgets.QVBoxLayout()
        self.combobox = QtWidgets.QComboBox()
        self.combobox.addItems(courseList)
        self.combobox.setCurrentText(combo_string)
        layout.addWidget(self.combobox)
        ok_button = QtWidgets.QPushButton("OK")
        layout.addWidget(ok_button)
        ok_button.clicked.connect(self.accept)
        self.setLayout(layout)

    def get_selected_item(self):
        return self.combobox.currentText()


class Ui_Dialog(object):
    # table_object = pd_obj()
    prevText = ""
    headers = []
    studentModel = QtGui.QStandardItemModel()
    courseModel = QtGui.QStandardItemModel()
    studentsCSV = pd.read_csv(studentsFile)
    courseCSV = pd.read_csv(courseFile)
    courseList = courseCSV['course'].tolist()
    model = QtGui.QStandardItemModel()
    '''1 is for student, 0 for course table'''
    tableMode = 1

    def setDialog(self):
        Dialog.setObjectName("Dialog")
        Dialog.resize(882, 761)
        Dialog.setMinimumSize(QtCore.QSize(882, 761))
        Dialog.setMaximumSize(QtCore.QSize(882, 9999))
        Dialog.setStyleSheet("background-color: rgb(39, 41, 50);\n"
                             "selection-color: rgb(255, 255, 255);\n"
                             "color: rgb(182, 194, 217);")

    def setTabs(self):
        self.tabWidget = QtWidgets.QTabWidget(parent=Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 861, 741))
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(9999, 9999))
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
                                     "                border: 2px solid rgb(130, 132, 137);\n"
                                     "            }\n"
                                     "            QTabBar::tab {\n"
                                     "                background-color: rgb(99, 101, 105);\n"
                                     "                color: rgb(245, 241, 224);\n"
                                     "            }\n"
                                     "            QTabBar::tab:selected {\n"
                                     "                background-color: rgb(130, 132, 137);\n"
                                     "            }\n"
                                     "")
        self.tabWidget.setObjectName("tabWidget")

        self.studentTab = QtWidgets.QWidget()
        self.studentTab.setObjectName("studentTab")

        self.courseTab = QtWidgets.QWidget()
        self.courseTab.setObjectName("courseTab")

    def addClicked(self):
        if self.lineEdit_name.text() and self.lineEdit_id.text() and self.comboBox.currentText():
            arrey = [self.lineEdit_name.text(), self.lineEdit_id.text(),
                     self.comboBox.currentText()]
            print(arrey)
            if (not pd_obj.studentInCSV(arrey)):
                pd_obj.addEntry(arrey)

                num_rows = self.studentModel.rowCount()

                self.studentModel.insertRow(num_rows)

                for column in range(self.studentModel.columnCount()):
                    self.prevText = arrey[column]
                    item = QtGui.QStandardItem(arrey[column])
                    self.studentModel.setItem(num_rows, column, item)

                self.studentModel.itemFromIndex(
                    self.studentModel.index(num_rows, 2)).setEditable(False)

    def setGroupBox_4(self):
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.studentTab)
        self.groupBox_4.setGeometry(QtCore.QRect(40, 50, 781, 121))
        self.groupBox_4.setStyleSheet("QGroupBox::title {color: rgb(245, 241, 224);}\n"
                                      "QGroupBox {border :2px solid rgb(232, 221, 181);\n"
                                      "                  border-width: 0 0 2px 0;}\n"
                                      "color: rgb(245, 241, 224);")
        self.groupBox_4.setObjectName("groupBox_4")

        self.lineEdit_name = QtWidgets.QLineEdit(parent=self.groupBox_4)
        self.lineEdit_name.setInputMask("")
        self.lineEdit_name.setText("")
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.lineEdit_name.setGeometry(QtCore.QRect(90, 20, 321, 31))
        self.lineEdit_name.setStyleSheet("border-style: none;\n"
                                         "border-bottom-style: solid;\n"
                                         "border-width: 0 0 2px 0;\n"
                                         "border-color: rgb(71, 115, 154);\n"
                                         "color: white;\n"
                                         "background-color: transparent;")

        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(245, 241, 224);")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.pushButton.setGeometry(QtCore.QRect(690, 70, 81, 31))
        self.pushButton.setStyleSheet("border-radius: 5px;\n"
                                      "color: rgb(245, 241, 224);\n"
                                      "border:2px solid rgb(71, 115, 154);/*2px solid rgb(33, 241, 54);*/")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.addClicked)
        self.lineEdit_id = QtWidgets.QLineEdit(parent=self.groupBox_4)
        self.lineEdit_id.setGeometry(QtCore.QRect(90, 70, 321, 31))
        self.lineEdit_id.setStyleSheet("border-style: none;\n"
                                       "border-bottom-style: solid;\n"
                                       "border-width: 0 0 2px 0;\n"
                                       "border-color: rgb(71, 115, 154);\n"
                                       "color: white;\n"
                                       "background-color: transparent;")
        self.lineEdit_id.setInputMask("")
        self.lineEdit_id.setText("")
        self.lineEdit_id.setObjectName("lineEdit_id")

        # EDIT
        self.comboBox = QtWidgets.QComboBox(parent=self.groupBox_4)
        csv_file = open('course.csv', newline='')
        reader = csv.reader(csv_file)
        next(reader)
        items = [row[0] for row in reader]
        self.comboBox.insertItems(1, items)
        self.comboBox.setGeometry(QtCore.QRect(610, 20, 161, 31))
        self.comboBox.setStyleSheet("border: 2px solid white;\n"
                                    "border-color:rgb(71, 115, 154);\n"
                                    "color: rgb(245, 241, 224);")
        self.comboBox.setObjectName("comboBox")

        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(245, 241, 224);")
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(440, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(245, 241, 224);")
        self.label_3.setObjectName("label_3")

    def search_table(self):
        if self.pushButton_3.text() is not None:
            search_string = self.lineEdit_name_3.text()
            # self.studentsCSV = pd.read_csv(studentsFile)
            for row in range(self.studentModel.rowCount()):
                match_found = False
                for column in range(self.studentModel.rowCount()-1):
                    print(
                        f"KOBEEE {self.studentModel.index(row, column).data(0)}")
                    temp = self.studentModel.index(row, column).data(0)
                    if temp is not None and search_string.lower() in temp.strip().lower():
                        match_found = True
                        break
                if match_found:
                    self.studentTable.setRowHidden(row, False)
                else:
                    self.studentTable.setRowHidden(row, True)

    def setSearch(self):
        self.label_8 = QtWidgets.QLabel(parent=self.studentTab)
        self.label_8.setGeometry(QtCore.QRect(30, 190, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(245, 241, 224);")
        self.label_8.setObjectName("label_8")

        self.lineEdit_name_3 = QtWidgets.QLineEdit(parent=self.studentTab)
        self.lineEdit_name_3.setGeometry(QtCore.QRect(130, 190, 321, 31))
        self.lineEdit_name_3.setStyleSheet("border-style: none;\n"
                                           "border-bottom-style: solid;\n"
                                           "border-width: 0 0 2px 0;\n"
                                           "border-color: rgb(71, 115, 154);\n"
                                           "color: white;\n"
                                           "background-color: transparent;")
        self.lineEdit_name_3.setInputMask("")
        self.lineEdit_name_3.setText("")
        self.lineEdit_name_3.setObjectName("lineEdit_name_3")

        self.pushButton_3 = QtWidgets.QPushButton(parent=self.studentTab)
        self.pushButton_3.setGeometry(QtCore.QRect(460, 190, 61, 31))
        self.pushButton_3.setStyleSheet("border-radius: 5px ;\n"
                                        "color: rgb(241, 234, 208);\n"
                                        "border :2px solid rgb(216, 17, 89);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.search_table)

    def delete_rows(self, arr, header):
        currentModel = self.studentModel if header != "course" else self.courseModel
        for row in arr:
            currentModel.removeRow(row)

    def delete_entry(self, header):
        print("delete_entry IS CALLED and header is")
        print(header)
        selection_model = self.studentTable.selectionModel(
        ) if header != "course" else self.courseTable.selectionModel()

        selected_indexes = selection_model.selectedIndexes()

        rows_to_remove = []
        for index in selected_indexes:
            if index.column() != 2:
                rows_to_remove.append(index.row())
        rows_to_remove.sort(reverse=True)
        if header != "course":
            print("if header != 'course':")
            pd_obj.deleteEntry(rows_to_remove)
        else:
            print("else:")
            self.delete_rows(rows_to_remove, "course")
            for index in rows_to_remove:
                print(
                    f"index in rows is {index}")
                self.courseList.pop(index)
            # get rows_to_remove for studentTable
            rows_to_remove = sorted(
                pd_obj.deleteCourse(rows_to_remove), reverse=True)
            self.comboBox.clear()
            self.comboBox.addItems(self.courseList)
        self.delete_rows(rows_to_remove, "not course")
        print(self.courseList)

    def setStudentTab(self):
        self.setGroupBox_4()
        self.setSearch()

        self.deleteStudentButton = QtWidgets.QPushButton(
            parent=self.studentTab)
        self.deleteStudentButton.setGeometry(QtCore.QRect(720, 190, 101, 31))
        self.deleteStudentButton.setStyleSheet("border-radius: 5px;\n"
                                               "color: rgb(241, 234, 208);\n"
                                               "border :2px solid rgb(216, 17, 89);")
        self.deleteStudentButton.setObjectName("deleteStudentButton")
        self.deleteStudentButton.clicked.connect(
            lambda header: self.delete_entry("not course"))

        self.tabWidget.addTab(self.studentTab, "")

    def modelSetter(self):
        self.headers = list(self.studentsCSV.columns)
        self.studentModel.setHorizontalHeaderLabels(
            self.studentsCSV.columns)

        self.headers2 = list(self.courseCSV.columns)
        self.courseModel.setHorizontalHeaderLabels(self.courseCSV.columns)

    def setModelStudent(self, pdCSV):
        model = QtGui.QStandardItemModel()
        for row in range(len(pdCSV)):
            for column in range(len(pdCSV.columns)):
                item = QtGui.QStandardItem(
                    str(pdCSV.iloc[row, column]))
                model.setItem(row, column, item)
                if column == 2:
                    item.setEditable(False)
        return model

    def addCourseClicked(self):
        print(
            f"{not (self.addCourseLine.text() is None or not self.addCourseLine.text())}")
        print(f"{self.addCourseLine.text() in self.courseList}")
        if not (self.addCourseLine.text() in self.courseList) and not (self.addCourseLine.text() is None or not self.addCourseLine.text()):
            pd_obj.addCourse(self.addCourseLine.text())
            self.courseModel.appendRow(
                [QtGui.QStandardItem(self.addCourseLine.text())])
            self.courseList.append(self.addCourseLine.text())
            self.comboBox.addItem(self.addCourseLine.text())

    def setCourseTab(self):
        self.courseLabel = QtWidgets.QLabel(parent=self.courseTab)
        self.courseLabel.setGeometry(QtCore.QRect(30, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.courseLabel.setFont(font)
        self.courseLabel.setStyleSheet("color: rgb(245, 241, 224);")
        self.courseLabel.setObjectName("courseLabel")

        self.addCourseLine = QtWidgets.QLineEdit(parent=self.courseTab)
        self.addCourseLine.setGeometry(QtCore.QRect(120, 80, 321, 31))
        self.addCourseLine.setStyleSheet("border-style: none;\n"
                                         "border-bottom-style: solid;\n"
                                         "border-width: 0 0 2px 0;\n"
                                         "border-color: rgb(71, 115, 154);\n"
                                         "color: white;\n"
                                         "background-color: transparent;")
        self.addCourseLine.setInputMask("")
        self.addCourseLine.setText("")
        self.addCourseLine.setObjectName("addCourseLine")

        self.addCourseButton = QtWidgets.QPushButton(parent=self.courseTab)
        self.addCourseButton.setGeometry(QtCore.QRect(470, 80, 61, 31))
        self.addCourseButton.setStyleSheet("border-radius: 5px ;\n"
                                           "color: rgb(241, 234, 208);\n"
                                           "border :2px solid rgb(216, 17, 89);")
        self.addCourseButton.setObjectName("addCourseButton")
        self.addCourseButton.clicked.connect(self.addCourseClicked)

        self.deleteCourseButton = QtWidgets.QPushButton(
            parent=self.courseTab)
        self.deleteCourseButton.setGeometry(QtCore.QRect(720, 80, 101, 31))
        self.deleteCourseButton.setStyleSheet("border-radius: 5px ;\n"
                                              "color: rgb(241, 234, 208);\n"
                                              "border :2px solid rgb(216, 17, 89);")
        self.deleteCourseButton.setObjectName("deleteCourseButton")
        # self.deleteCourseButton.clicked.connect(self.delete_entry)
        self.deleteCourseButton.clicked.connect(
            lambda header: self.delete_entry("course"))

    def setSModel(self):
        # self.studentsCSV = pd.read_csv(studentsFile)
        # self.courseCSV = pd.read_csv(courseFile)
        self.courseList = self.courseCSV['course'].tolist()

        self.studentModel = self.setModelStudent(self.studentsCSV)
        self.courseModel = self.setModelStudent(self.courseCSV)
        self.modelSetter()

        # Populate the table with some data
        self.setComposeTable()

    def printTable(self):
        # if self.tableMode == 1:
        for row in range(self.studentModel.rowCount()):
            for column in range(self.studentModel.columnCount()-1):
                index = self.studentModel.index(row, column)
                item = self.studentModel.itemFromIndex(index)
                print(item.text())
                self.studentModel.setItem(row, column, item)
                if column == 2:
                    item.setEditable(False)
        '''
        for row in range(self.studentModel.rowCount()):
            index = self.studentModel.index(row, 2)
            item = self.studentModel.itemFromIndex(index)
            item.setEditable(False)
        '''

        for row in range(self.courseModel.rowCount()):
            index = self.courseModel.index(row, 0)
            item = self.courseModel.itemFromIndex(index)
            self.courseModel.setItem(row, 0, item)

    def on_student_selection_changed(self, current_index, previous_index):
        column = current_index.column()
        row = current_index.row()
        self.prevText = self.studentModel.data(current_index)
        print(
            f"Selected cell: column={column}, row={row}, text='{self.prevText}'")

    def on_course_selection_changed(self, current_index, previous_index):
        column = current_index.column()
        row = current_index.row()
        self.prevText = self.courseModel.data(current_index)
        print(
            f"Selected cell: column={column}, row={row}, text='{self.prevText}'")

    def handle_tab_changed(self, index):
        index = not index
        elementNum = 4 if index else 5
        # i = 0 for widget in self.tabWidget.widget(index).children(): print(f"{widget.objectName()}: {i}") i += 1 print("-------------------------------")
        previous_tableview = self.tabWidget.widget(index).children()[
            elementNum]

        previous_tableview.selectionModel().clearSelection()
        previous_tableview.clearFocus()

    def setComposeTable(self):
        self.studentTable = QtWidgets.QTableView(parent=self.studentTab)
        self.studentTable.setGeometry(QtCore.QRect(40, 240, 781, 441))
        self.studentTable.setObjectName("studentTable")
        self.studentTable.setModel(self.studentModel)
        self.studentTable.horizontalHeader().setSectionResizeMode(
            QtWidgets.QHeaderView.ResizeMode.Stretch)

        self.courseTable = QtWidgets.QTableView(parent=self.courseTab)
        self.courseTable.setGeometry(QtCore.QRect(40, 150, 781, 531))
        self.courseTable.setObjectName("courseTable")
        self.courseTable.setModel(self.courseModel)
        self.courseTable.horizontalHeader().setSectionResizeMode(
            QtWidgets.QHeaderView.ResizeMode.Stretch)

        # self.printTable()
        self.is_editable = False

        self.studentModel.itemChanged.connect(
            lambda item, header="": self.edit_cell(item, self.studentModel.headerData(item.column(), Qt.Orientation.Horizontal)))

        self.studentTable.selectionModel().currentChanged.connect(
            self.on_student_selection_changed)

        self.studentTable.setModel(self.studentModel)
        self.studentTable.clicked.connect(self.set_prev_text)
        self.studentTable.setStyleSheet(tableStyleSheet)

        self.courseModel.itemChanged.connect(
            lambda item, header="": self.edit_cell(item, self.courseModel.headerData(item.column(), Qt.Orientation.Horizontal)))
        self.courseTable.selectionModel().currentChanged.connect(
            self.on_course_selection_changed)
        self.courseTable.setStyleSheet(tableStyleSheet)

        self.tabWidget.currentChanged.connect(self.handle_tab_changed)

    def setupUi(self, Dialog):

        self.setDialog()
        self.setTabs()
        self.setStudentTab()
        self.setCourseTab()
        self.setSModel()

        # ----------------------------------------------------------------------------------

        self.label_9 = QtWidgets.QLabel(parent=self.studentTab)
        self.label_9.setGeometry(QtCore.QRect(20, 10, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(245, 241, 224);")
        self.label_9.setObjectName("label_9")
        self.label = QtWidgets.QLabel(parent=self.courseTab)
        self.label.setGeometry(QtCore.QRect(20, 10, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(245, 241, 224);")
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.courseTab, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def editCourseNameinSTable(self, oldInfo, newInfo):
        print("updateCourses called !!!")
        print(self.courseList)

        # edit "course" in student Table when text in that row == oldInfo
        column = 2
        for row in range(self.studentModel.rowCount()):
            index = self.studentModel.index(row, column)
            item = self.studentModel.itemFromIndex(index)
            if item.text() == oldInfo:
                item.setText(newInfo)

        self.comboBox.clear()
        self.comboBox.addItems(self.courseList)

    def edit_cell(self, item, header):
        print("edit_cellllll")
        row = item.row()
        columnNumber = item.column()
        column = self.headers[columnNumber]
        new_text = item.text()
        print(f"new text is {new_text}")
        previous_text = self.prevText if self.prevText != "" else new_text
        inCourse = not pd_obj.notInCSV(new_text, "course", 0)
        inStudent = not pd_obj.notInCSV(new_text, column, 1)
        if previous_text != new_text:
            if new_text != "":
                if header == "course" and not inCourse:
                    print("editCourse")
                    pd_obj.editCourse(previous_text, new_text)
                    self.courseList[row] = self.prevText = new_text
                    self.editCourseNameinSTable(
                        oldInfo=previous_text, newInfo=new_text)
                elif header == "course" and inCourse:
                    print("editCourse failed")
                    self.courseModel.item(
                        row, columnNumber).setText(previous_text)
                elif not inStudent:
                    print("editEntry")
                    pd_obj.editEntry(previous_text,
                                     new_text, column)
                    # pd_obj.editEntry(self, previous_text, new_text, 'course')
                elif inStudent:
                    print("editEntry failed")
                    self.studentModel.item(
                        row, columnNumber).setText(previous_text)
                self.prevText = new_text
                print(f"self.prevText: {self.prevText}")

            else:
                print("text failed")
                print(
                    f"column is {column}, while previous_text is {previous_text}")
                print(f"new_text is {new_text}")
                prevInStudent = not pd_obj.notInCSV(
                    previous_text, column, 1)
                prevInCourse = not pd_obj.notInCSV(
                    previous_text, "course", 0)
                if prevInStudent:
                    self.studentModel.blockSignals(True)
                    self.studentModel.item(
                        row, columnNumber).setText(previous_text)
                    self.studentModel.blockSignals(False)
                elif prevInCourse:
                    self.courseModel.blockSignals(True)
                    self.courseModel.item(
                        row, columnNumber).setText(previous_text)
                    self.courseModel.blockSignals(False)
        print(self.courseList)

    def set_prev_text(self, index):
        if index.column() == 2:
            # self.prevText = index.data()
            dialog = CoursePopUp(Dialog, self.courseList, index.data())
            if dialog.exec() == 1:
                newCourse = dialog.get_selected_item()
                if index.data() != newCourse:
                    idNumber = self.studentTable.model().index(
                        index.row(), index.column()-1).data()
                    pd_obj.editEntryCourse(idNumber, newCourse)
                    self.studentModel.blockSignals(True)
                    item = QtGui.QStandardItem(newCourse)
                    self.studentModel.setItem(index.row(), 2, item)
                    self.studentModel.blockSignals(False)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        # self.editEntryButton.setText(_translate("Dialog", "EDIT: OFF"))
        self.deleteStudentButton.setText(_translate("Dialog", "DELETE ENTRY"))
        self.label_9.setText(_translate(
            "Dialog", "Simple Student Information System (SSIS)"))
        self.lineEdit_name_3.setPlaceholderText(
            _translate("Dialog", "Enter Name or ID"))
        self.label_8.setText(_translate("Dialog", "  Search"))
        self.pushButton_3.setText(_translate("Dialog", "SEARCH"))
        self.groupBox_4.setTitle(_translate("Dialog", "Add Student"))
        self.lineEdit_name.setPlaceholderText(
            _translate("Dialog", "Enter name of student"))
        self.label_2.setText(_translate("Dialog", "   Name"))
        self.pushButton.setText(_translate("Dialog", "ADD"))
        self.lineEdit_id.setPlaceholderText(
            _translate("Dialog", "Enter ID of student"))
        self.label_4.setText(_translate("Dialog", "       ID"))
        self.label_3.setText(_translate("Dialog", "      Course"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.studentTab), _translate("Dialog", "Student"))
        self.addCourseLine.setPlaceholderText(
            _translate("Dialog", "Add Course"))
        self.courseLabel.setText(_translate("Dialog", "  Course"))
        self.addCourseButton.setText(_translate("Dialog", "ADD"))
        self.label.setText(_translate(
            "Dialog", "Simple Student Information System (SSIS)"))
        # self.editCourseButton.setText(_translate("Dialog", "EDIT: OFF"))
        self.deleteCourseButton.setText(
            _translate("Dialog", "DELETE ENTRY"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.courseTab), _translate("Dialog", "Course"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
